server:
  port: 8081

app:
  redirect-url: "http://localhost:3000/"
  otp:
    expiration-time: "5"

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
        
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  # sql:
  #   init:
  #     mode: always
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLINET_ID}
            client-secret: ${GITHUB_CLINET_SECRET}
            scope: ${GITHUB_CLINET_SCOPE}
            redirect-uri: ${GITHUB_CLINET_REDIRECT_URI}
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
